### PR TITLE
Mastery ID refactoring to use identifiers.

### PR DESCRIPTION
**Pull request by christian-gallagher**
## Summary
Adjust the code-completion templates for Mastery to account for identifiers being used for IDs.

Needs: https://github.com/finos/legend-engine/pull/1102

## How did you test this change?

No other changed required because the JSON protocol is unchanged, the engine code takes care of moving the ID to an identifier supplied as a name.

### CODE REVIEW

**Review by MauricioUyaguari — DISMISSED** [review]

**Comment by MauricioUyaguari** [comment]
@christian-gallagher please link corresponding engine ticket to this. We can merge once engine is out . Thanks

**Comment by christian-gallagher** [comment]
> @christian-gallagher please link corresponding engine ticket to this. We can merge once engine is out . Thanks

This is the Engine PR - https://github.com/finos/legend-engine/pull/1091

Given the changes are only to the auto complete text this is not a hard dependency, the MAstery config has not been rolled out to clients yet so only the Mastery team will se the auto-complete is not correct.

**Comment by christian-gallagher** [comment]
The engine change (https://github.com/finos/legend-engine/pull/1091) has been merged.

**Comment by christian-gallagher** [comment]
1090 was reverted, this change now requires the following PR on the back end.
https://github.com/finos/legend-engine/pull/1102

**Comment by MauricioUyaguari** [comment]
@christian-gallagher please fix your build as it is currently red. You need a valid changeset

**Review by MauricioUyaguari — APPROVED** [review]

**Pull request merged**
