### PR TITLE
Replace query builder setup icons with text

### PR DESCRIPTION
**Pull request by travisstebbins**
## Summary

Restyle the execution context panel in all query builder windows to replace symbols with text to make it easier for users to interpret the UI.

## How did you test this change?

- [x] Test(s) added
- [x] Manual testing (please provide screenshots/recordings)
- [ ] No testing (please provide an explanation)

Class query builder:
ClassQueryBuilder

Database query builder:
DatabaseQueryBuilder

Mapping execution query builder:
MappingExecutionQueryBuilder

Service query builder:
ServiceQueryBuilder

### CODE REVIEW

**Comment by MauricioUyaguari** [comment]
Thinking about this, lets just remove the layering "Properties". We had it around the execution context before (depending on which query builder state it meant different things). We can add a header above these selections called Properties but it would be on top of the panel not as a left right border.

**Comment by YannanGao-gs** [comment]
Hello @travisstebbins, it's just my preference... Text aligned to the right looks a little weird 😅

**Comment by travisstebbins** [comment]
> Hello @travisstebbins, it's just my preference... Text aligned to the right looks a little weird 😅

I'm open to left or right aligned. I figured right aligned would keep the spacing between the right edge of the text and the left edge of the selector consistent.

**Comment by travisstebbins** [comment]
Closing this PR in favor of https://github.com/finos/legend-studio/pull/3146 since the gs-opensource-bot reverts any commits made to this branch.

**Pull request closed without merging**
