### PR TITLE
feat: Class editor: allow DnD to rearrange properties

### PR DESCRIPTION
**Pull request by xannem**
Kapture 2022-07-29 at 11 52 29

### CODE REVIEW

**Comment by akphi** [comment]
@finos-cla-bot[bot] check

**Comment by akphi** [comment]
@finos-cla-bot[bot] check

**Comment by akphi** [comment]
@finos-cla-bot[bot] check

**Comment by akphi** [comment]
@finos-cla-bot[bot] check

**Comment by akphi** [comment]
@finos-cla-bot[bot] check

**Comment by TheJuanAndOnly99** [comment]
@finos-cla-bot[bot] check

**Comment by TheJuanAndOnly99** [comment]
@cla-bot[bot] check

**Comment by akphi** [comment]
@cla-bot[bot] check

**Comment by akphi** [comment]
@TheJuanAndOnly99 seems like it still didn't work. Does @xannem need to repush or something?

**Comment by akphi** [comment]
@cla-bot[bot] check

**Comment by TheJuanAndOnly99** [comment]
hi @akphi I think the bot is having issues. Give me a few minutes and I'll solve it

**Comment by TheJuanAndOnly99** [comment]
@cla-bot[bot] check

**Comment by TheJuanAndOnly99** [comment]
@akphi sorry about the issues. should be all set now!

**Comment by TheJuanAndOnly99** [comment]
@cla-bot[bot] check

**Comment by TheJuanAndOnly99** [comment]
@xannem are you able to close this PR and open a new one? The cla-bot got stuck on this one. But you are now covered and this wont happen again.

**Comment by akphi** [comment]
Thanks @TheJuanAndOnly99. Things look good now!

**Pull request closed without merging**
