### PR TITLE
Flat-data: handle multi-date formats

### PR DESCRIPTION
**Pull request by aziemchawdhary-gs**
* FlatData: Handle multi-date formats

* Fix equality typo

* WIP: (de)serializer fixes for flatdata properties

* WIP fix serialization

* try out fixing test data

* review comments and test fix

* Fix linting errors

## How did you test this change?

- [ ] Test(s) added
- [ ] Manual testing (please provide screenshots/recordings)
- [ ] No testing (please provide an explanation)

### CODE REVIEW

**Comment by akphi** [comment]
Should we close out https://github.com/finos/legend-studio/pull/1402 in favor of this PR?

**Comment by aziemchawdhary-gs** [comment]
> Should we close out #1402 in favor of this PR?

I hadn't spotted #1402 : I don't mind, this PR is a cherry-pick of my original change that was reverted

**Comment by akphi** [comment]
Okie, I'll close #1402 in favor of this then.

**Comment by akphi** [comment]
@aziemchawdhary-gs could you please rebase and get this PR ready? Thanks!

**Comment by aziemchawdhary-gs** [comment]
> @aziemchawdhary-gs could you please rebase and get this PR ready? Thanks!

Done

**Review by MauricioUyaguari — APPROVED** [review]

**Pull request merged**
