### PR TITLE
Add support for transaction derivation in persistence model

### PR DESCRIPTION
**Pull request by davidsunglee**
## Summary

Dependencies:
legend-engine: https://github.com/finos/legend-engine/pull/664

## How did you test this change?

- [x] Test(s) added
- [x] Manual testing (please provide screenshots/recordings)
- [ ] No testing (please provide an explanation)

### CODE REVIEW

**Comment by rafaelbey** [comment]
Thanks for including the exports.  Few things I think will make it easier for people importing these:

- Can we also add a method here to `resolvePersistence`?

https://github.com/finos/legend-studio/blob/master/packages/legend-graph/src/models/protocols/pure/v1/transformation/pureGraph/to/V1_GraphBuilderContext.ts

- Wonder if we should also add `PERSISTENCE` enum here:

https://github.com/finos/legend-studio/blob/master/packages/legend-graph/src/models/protocols/pure/v1/model/packageableElements/V1_PackageableElement.ts#L78

**Comment by davidsunglee** [comment]
> Thanks for including the exports. Few things I think will make it easier for people importing these:
> 
> * Can we also add a method here to `resolvePersistence`?
> 
> https://github.com/finos/legend-studio/blob/master/packages/legend-graph/src/models/protocols/pure/v1/transformation/pureGraph/to/V1_GraphBuilderContext.ts
> 
> * Wonder if we should also add `PERSISTENCE` enum here:
> 
> https://github.com/finos/legend-studio/blob/master/packages/legend-graph/src/models/protocols/pure/v1/model/packageableElements/V1_PackageableElement.ts#L78

Would these changes introduce an unwanted dependency on the Persistence DSL module? The second only adds a String, so it's only a conceptual dependency, but the first would be a hard one.

**Comment by akphi** [comment]
@davidsunglee seems like the test for persistence is failing - https://github.com/finos/legend-studio/runs/6528100151?check_suite_focus=true . We will skip that test for now, could you please fix that test? Thanks!

**Comment by davidsunglee** [comment]
> @davidsunglee seems like the test for persistence is failing - https://github.com/finos/legend-studio/runs/6528100151?check_suite_focus=true . We will skip that test for now, could you please fix that test? Thanks!

@akphi Sorry for delay, been out the last week. This test passes for yarn:ci in the context of this PR, so I'll uncomment as part of this change. The engine change required for this PR has been merged but I believe release is still pending.

**Comment by davidsunglee** [comment]
@akphi @MauricioUyaguari Please review when you have a moment. Thanks!

**Review by akphi — DISMISSED** [review]
@davidsunglee Looks good to me. Let's merge this when https://github.com/finos/legend-studio/pull/1108 is merged. Also, please remember to uncomment the grammar roundtrip test.

Also, I'm not sure if you need to export everything in `ProtocolHelper` and `metamodels` or not, I usually do this sparingly in core modules like `@finos/legend-graph` as it pollutes the import space and degrades IDE performance. But you author this plugin so it's totally your call.

Please keep us posted on when we can merge this.

**Comment by davidsunglee** [comment]
@rafaelbey Re: An's comment about exports -- I think you need everything in metamodels. Do you also need access to *ModelSchema or serialize*/deserialize* functions in ProtocolHelpers?

**Comment by rafaelbey** [comment]
I think we should expose the packageable elements, since these are the ones that others will depend on.  

But to help decide, let me show what I depend at the moment:

```tsx
// todo disable eslint until persistence is exported - https://github.com/finos/legend-studio/pull/1108
// eslint-disable-next-line @finos/legend-studio/no-cross-workspace-non-export-usage
import { Persistence } from '@finos/legend-extension-dsl-persistence/lib/models/metamodels/pure/model/packageableElements/persistence/DSLPersistence_Persistence';
```

```typescript
// eslint-disable-next-line @finos/legend-studio/no-cross-workspace-non-export-usage
import { V1_Persistence } from '@finos/legend-extension-dsl-persistence/lib/models/protocols/pure/v1/model/packageableElements/persistence/V1_DSLPersistence_Persistence';
```

```typescript
          // todo replace with context.resolvePersistence() once added/released - https://github.com/finos/legend-studio/pull/1108
          metamodel.persistence = context.resolveElement(
            protocol.persistence.path,
            false,
          ) as PackageableElementImplicitReference<Persistence>;
```

@davidsunglee  - One thing - with the discussion we are having around enhance persistence context, I suspect we wont need any of this since the persistence module itself will handle everything (?)

**Comment by davidsunglee** [comment]
@rafaelbey That's a good point. We still might need context subtypes to handle e.g. on premise-specific attributes. But either way, I'll reduce export scope to packageable elements, for this PR.

**Comment by davidsunglee** [comment]
@akphi @rafaelbey I think we're ready to merge this one (Engine changes from https://github.com/finos/legend-engine/pull/664 went in sometime back ...)

**Comment by akphi** [comment]
@davidsunglee What about the skipped roundtrip test?

**Comment by davidsunglee** [comment]
@akphi Probably my confusion: I removed the test entirely from the exclusions list, and it looks like it ran in the last roundtrip check (https://github.com/finos/legend-studio/runs/6939226739?check_suite_focus=true). Let me know if I need to do something else ...

**Review by akphi — APPROVED** [review]

**Pull request merged**
